### ISSUE TITLE
Error if key in both tables doesn't match

### ISSUE THREAD

**Issue by pablomayobre** [flamendless/lovely-windows#1]
If you passed a width table like the following one:
```lua
local width = {
  a = 300
}
```
And a height table like this:
```lua
local height = {
  b = 300
}
```
Then you call:
```lua
window.addInputTable(width, height)
window.keyInput("a")
```
It will error with `love.window.setMode argument #2 expected number, was nil`

Similar thing happens if you have:
```lua
local height = {
  a = "hello world"
}
```

My recommendation would be to accept a table formatted like this:
```lua
local tab = {
  a = { 300, 400 } --width, height
}
```
Then in your code you can define `addInputTable` like this:
```lua
function WINDOW.addInputTable(tab)
  if type(tab) == "table" then
    for k,v in pairs(tab) do
      if type(v) == "table" and tonumber(v[1]) and tonumber(v[2]) then
        WIDTH[k] = tonumber(v[1])
        HEIGHT[k] = tonumber(v[2])
      end
    end
  end
end
```
or:
```lua
function WINDOW.addInputTable(tab)
  if type(tab) == "table" then
    for k,v in pairs(tab) do
      if type(v) == "table" and tonumber(v[1]) and tonumber(v[2]) then
        MODE[k] = { tonumber(v[1]), tonumber(v[2]) }
      end
    end
  end
end

function WINDOW.switch(key)
  if canSwitch then
    love.window.setMode(unpack(MODE[key]))
    WINDOW.initialize(_window.gameWidth,_window.gameHeight)
    canSwitch = false
  end
end
```

Also the timeout is a little big, you may want to reduce it

**Comment by flamendless** [comment]
Yes, that will not work because the table identifier is different. It must be the same.

Yes, Im working on the library right now, and i did implement that new and better way. Thanks for suggesting also

**Comment by pablomayobre** [comment]
Got ninjaed in my edit hahaha 😋

**Comment by flamendless** [comment]
What do you mean? Ninja-ed?

**Comment by pablomayobre** [comment]
You commented before I finished editing

**Comment by pablomayobre** [comment]
This issue is not entirely fixed, try:
```lua
local tab = {
  a = { "hello world" }
}
```

**Comment by flamendless** [comment]
I suppose that wont work. What do you suggest?
