### ISSUE TITLE
Free license

### ISSUE THREAD

**Issue by ghost** [flamendless/lovely-windows#2]
_"This module/library is free. Do what you want."_ won't work in court. If you want people to be able to use your library freely, I highly recommend a proper free license such as the Apache License 2.0. Without a proper free license on your project, few people will want to use it because you may be able to sue them.

https://help.github.com/articles/licensing-a-repository/
https://opensource.guide/legal/

**Comment by flamendless** [comment]
Okay. Thanks for telling me. I will add it later

**Comment by flamendless** [comment]
License already provided
